---
- name: Update hostname of Cisco IOS router
  hosts: r2
  gather_facts: no
  tasks:
    - name: Update hostname
      cisco.ios.ios_config:
        lines:
          - hostname r5
        save_when: always
