---
- name: Update hostname of Cisco IOS router
  hosts: r1
  gather_facts: no
  tasks:
    - name: Update hostname
      cisco.ios.ios_config:
        lines:
          - hostname r2
        save_when: always
